import { Category, Product } from '@/types';

// ═══════════════════════════════════════════════════════════
// CATEGORÍAS
// ═══════════════════════════════════════════════════════════
export const categories: Category[] = [
  { id: 'cat-1', name: 'Infusiones y Tés',    slug: 'infusiones-y-tes',   icon: '🍵', sort_order: 1, description: 'Blends herbales para el bienestar y el equilibrio' },
  { id: 'cat-2', name: 'Cuidado Capilar',     slug: 'cuidado-capilar',    icon: '💆', sort_order: 2, description: 'Tratamientos naturales para tu cabello' },
  { id: 'cat-3', name: 'Cuidado de Uñas',     slug: 'cuidado-de-unas',    icon: '💅', sort_order: 3, description: 'Productos libres de tóxicos para tus manos' },
  { id: 'cat-4', name: 'Higiene Personal',    slug: 'higiene-personal',   icon: '🪥', sort_order: 4, description: 'Rutina diaria con ingredientes conscientes' },
  { id: 'cat-5', name: 'Cuidado Corporal',    slug: 'cuidado-corporal',   icon: '🌿', sort_order: 5, description: 'Nutre tu piel con lo mejor de la naturaleza' },
  { id: 'cat-6', name: 'Cuidado para Él',     slug: 'cuidado-para-el',    icon: '🧴', sort_order: 6, description: 'Grooming natural y consciente' },
  { id: 'cat-7', name: 'Snacks y Bienestar',  slug: 'snacks-y-bienestar', icon: '✨', sort_order: 7, description: 'Alimentos naturales y productos de bienestar' },
];

// ═══════════════════════════════════════════════════════════
// PRODUCTOS
// Importado desde: UMA PRODUCTOS.xlsx
// Fecha: 2026-08-05 11:19
// Herramienta: uma_migrate.py
// ═══════════════════════════════════════════════════════════
export const products: Product[] = [
  {
    id: 'p-001', slug: 'almendras-50-g', name: 'Almendras - 50 g',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Un snack nutritivo y equilibrado, rico en grasas saludables y minerales esenciales.',
    description: 'Un snack nutritivo y equilibrado, rico en grasas saludables y minerales esenciales.\n\nCaracterísticas y beneficios:\n✨ Fuente natural de proteína vegetal\n✨ Aportan energía sostenida durante el día\n✨ Ricas en vitamina E y antioxidantes\n✨ Favorecen la salud de la piel y el cabello\n✨ Apoyan la sensación de sacieda',
    benefits: ['Antioxidante'],
    price: 6000, price_label: '/ 50 g',
    image_url: '/productos/almendras-50-g.jpg',
    images: [],
    tags: ['no-crop', 'natural', 'snack'],
    is_featured: false, is_available: true, sort_order: 1,
  },
  {
    id: 'p-002', slug: 'cardamomo-20-g', name: 'Cardamomo – 20 g',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Una especia aromática de tradición ancestral, apreciada por su aroma intenso y propiedades digestivas.',
    description: 'Una especia aromática de tradición ancestral, apreciada por su aroma intenso y propiedades digestivas.\n\nCaracterísticas y beneficios:\n✨ Favorece la digestión y reduce la pesadez estomacal\n✨ Aroma cálido y estimulante\n✨ Propiedades antioxidantes naturales\n✨ Ideal para infusiones, tés y preparaciones especiales\n✨ Aporta equilibrio y bienestar digestivo',
    benefits: ['Antioxidante', 'Digestivo'],
    price: 78000, price_label: '/ 20 g',
    image_url: '/productos/cardamomo-20-g.jpg',
    images: [],
    tags: ['natural', 'snack'],
    image_fit: 'cover',
    image_position: 'center center',
    is_featured: false, is_available: true, sort_order: 2,
  },
  {
    id: 'p-003', slug: 'nuez-de-brasil-50-g', name: 'Nuez de Brasil – 50 g',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Un fruto seco premium reconocido por su alto valor nutricional y textura suave.',
    description: 'Un fruto seco premium reconocido por su alto valor nutricional y textura suave.\n\nCaracterísticas y beneficios:\n✨ Rica en selenio, mineral clave antioxidante\n✨ Apoya el sistema inmunológico\n✨ Fuente de grasas saludables\n✨ Contribuye al bienestar hormonal y energético\n✨ Snack nutritivo y saciante',
    benefits: ['Antioxidante'],
    price: 8500, price_label: '/ 50 g',
    image_url: '/productos/nuez-de-brasil-50-g.jpg',
    images: [],
    tags: ['eco-friendly', 'snack'],
    image_fit: 'cover',
    image_position: 'center center',
    is_featured: false, is_available: true, sort_order: 3,
  },
  {
    id: 'p-004', slug: 'semillas-de-calabaza-50-g', name: 'Semillas de calabaza – 50 g',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Un snack funcional y lleno de nutrientes, ideal para fortalecer el cuerpo y complementar una alimentación consciente.',
    description: 'Un snack funcional y lleno de nutrientes, ideal para fortalecer el cuerpo y complementar una alimentación consciente.\n\nCaracterísticas y beneficios:\n✨ Alta fuente de proteína vegetal\n✨ Ricas en magnesio y zinc\n✨ Apoyan la salud del sistema inmunológico\n✨ Contribuyen al bienestar del sistema nervioso\n✨ Favorecen la energía y recuperación muscular',
    benefits: ['Fortalecedor'],
    price: 5800, price_label: '/ 50 g',
    image_url: '/productos/semillas-de-calabaza-50-g.jpg',
    images: ['/productos/semillas-de-calabaza-50-g-g-snack-saludable-1.jpg'],
    tags: ['snack'],
    is_featured: false, is_available: true, sort_order: 4,
  },
  {
    id: 'p-005', slug: 'semillas-de-girasol-50-g', name: 'Semillas de girasol – 50 g',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Un alimento versátil y nutritivo, perfecto para consumir entre comidas o añadir a tus preparaciones diarias.',
    description: 'Un alimento versátil y nutritivo, perfecto para consumir entre comidas o añadir a tus preparaciones diarias.\n\nCaracterísticas y beneficios:\n✨ Fuente de grasas saludables\n✨ Ricas en vitamina E y antioxidantes\n✨ Apoyan la salud cardiovascular\n✨ Contribuyen al cuidado de la piel\n✨ Aportan energía natural y sostenida',
    benefits: ['Antioxidante'],
    price: 4000, price_label: '/ 50 g',
    image_url: '/productos/semillas-de-girasol-50-g.webp',
    images: ['/productos/semillas-de-girasol-50-g-g-l-almendras-calabaza.jpg'],
    tags: ['no-crop', 'natural', 'snack'],
    is_featured: false, is_available: true, sort_order: 5,
  },
  {
    id: 'p-006', slug: 'shampoo-para-barba', name: 'Shampoo para Barba',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Limpieza profunda y cuidado natural para tu barba y piel.',
    description: 'Limpieza profunda y cuidado natural para tu barba y piel. Formulado con aceites esenciales de salvia, menta y árbol de té, reconocidos por sus propiedades purificantes y refrescantes.\n\nAyuda a prevenir la caspa en la barba, reduce la aparición de vellos encarnados y granitos, mientras estimula la circulación sanguínea en los folículos, favoreciendo una barba más sana, fresca y bien cuidada.\n\n✨ Ideal para:\n• Limpieza diaria de la barba\n• Prevenir irritaciones y descamación\n• Mantener la piel equilibrada\n• Cuidado y bienestar del vello facial',
    benefits: ['Natural'],
    price: 19000, price_label: '',
    image_url: '/productos/shampoo-para-barba.jpg',
    images: [],
    tags: ['natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 6,
  },
  {
    id: 'p-007', slug: 'tetera-de-vidrio-con-infusor-removible', name: 'Tetera de Vidrio con Infusor Removible',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Una pieza práctica y elegante diseñada para disfrutar tus infusiones favoritas con comodidad y estilo.',
    description: 'Una pieza práctica y elegante diseñada para disfrutar tus infusiones favoritas con comodidad y estilo. Elaborada en vidrio resistente al calor, permite preparar tés y mezclas naturales conservando su aroma y pureza.\n\nCuenta con infusor interno removible, ideal para controlar la intensidad de la infusión, y boquilla antigoteo que facilita un servido limpio y preciso.\n\n✨ Características:\n• Vidrio resistente a altas temperaturas\n• Infusor interno removible\n• Boquilla antigoteo\n• Preparación práctica y limpia\n• Ideal para tés e infusiones naturales\n\n🌿 Perfecta para acompañar rituales de té y momentos de pausa consciente.',
    benefits: ['Natural'],
    price: 60000, price_label: '',
    image_url: '/productos/tetera-de-vidrio-con-infusor-removible.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 7,
  },
  {
    id: 'p-008', slug: 'lampara-donut-luz-para-tus-momentos-de-calma', name: 'Lámpara Donut - Luz para tus momentos de Calma',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Convierte cualquier espacio en un ambiente acogedor con esta lámpara diseñada para acompañarte en tus momentos de descanso, lectura o...',
    description: 'Convierte cualquier espacio en un ambiente acogedor con esta lámpara diseñada para acompañarte en tus momentos de descanso, lectura o relajación. Su forma tipo donut y diseño minimalista la hacen perfecta para darle un toque moderno y cálido a tu hogar 🌙\n\n💡 Cuenta con 3 tonos de luz que puedes ajustar fácilmente con su sistema táctil, adaptándose a cada momento del día: desde una luz suave para descansar hasta una más clara para leer cómodamente.\n\n🔌 Se utiliza con cable USB, ideal para usarla de forma práctica en diferentes espacios.\n\n🪵 Su diseño versátil te permite usarla sobre mesa o colgarla en la pared, aprovechando mejor tus espacios.\n\n📏 Medidas:\n• Diámetro: 22.5 cm\n• Grosor: 7 cm\n\n✨ Ilumina tu espacio con calidez, estilo y funcionalidad.',
    benefits: ['Natural'],
    price: 98000, price_label: '',
    image_url: '/productos/lampara-donut-luz-para-tus-momentos-de-calma.jpg',
    images: [],
    tags: [],
    is_featured: false, is_available: true, sort_order: 8,
  },
  {
    id: 'p-009', slug: 'maquina-de-afeitar-reutilizable', name: 'Máquina de afeitar reutilizable',
    brand: 'UMA', category_id: 'cat-6',
    short_desc: 'Una alternativa práctica y sostenible para el cuidado personal diario.',
    description: 'Una alternativa práctica y sostenible para el cuidado personal diario. Diseñada para un afeitado preciso y cómodo, esta máquina reutilizable con cuchillas intercambiables permite un corte limpio mientras reduce el uso de plásticos desechables.\n\nSu estructura resistente ofrece mayor control durante el afeitado, ayudando a disminuir la irritación y logrando un acabado suave y uniforme.\n\n✨ Características:\n• Sistema de cuchillas intercambiables\n• Diseño reutilizable y duradero\n• Afeitado preciso y uniforme\n• Menor impacto ambiental\n• Fácil limpieza y mantenimiento',
    benefits: ['Natural'],
    price: 38000, price_label: '',
    image_url: '/productos/maquina-de-afeitar-reutilizable.jpg',
    images: [],
    tags: [],
    image_fit: 'cover',
    image_position: 'center center',
    is_featured: false, is_available: true, sort_order: 9,
  },
  {
    id: 'p-010', slug: 'te-rooibos-vainilla-20g', name: 'Té Rooibos Vainilla-20g',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Disfruta de un momento de calma y bienestar con esta mezcla suave y reconfortante, perfecta para acompañarte en tus espacios de descanso...',
    description: 'Disfruta de un momento de calma y bienestar con esta mezcla suave y reconfortante, perfecta para acompañarte en tus espacios de descanso o desconexión. Su sabor cálido y ligeramente dulce crea una experiencia envolvente desde el primer sorbo 🌙\n\n🌿 Elaborado a base de rooibos, una infusión naturalmente libre de cafeína, ideal para cualquier momento del día, incluso en la noche.\n\n🥥 Su mezcla con almendras, coco, pétalos de rosa y vainilla aporta notas delicadas, cremosas y florales que equilibran perfectamente el sabor, creando una bebida armoniosa y agradable.\n\n💛 Beneficios:\n• Relajante, ideal para bajar el ritmo del día\n• Digestivo y suave con el cuerpo\n• Aporta al equilibrio emocional\n• Fuente de antioxidantes, hierro y magnesio\n• No contiene teína\n\n🍃 Ingredientes:\nRooibos, almendras, coco, pétalos de rosa y vainilla\n\n✨ Una infusión pensada para reconectar contigo, bajar el ritmo y disfrutar lo simple.\nI',
    benefits: ['Antioxidante', 'Digestivo', 'Relajante'],
    price: 25000, price_label: '/ 20g',
    image_url: '/productos/te-rooibos-vainilla-20g.jpg',
    images: [],
    tags: ['no-crop', 'natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 10,
  },
  {
    id: 'p-011', slug: 'te-rooibos-vainilla-35g', name: 'Té Rooibos Vainilla-35g',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Disfruta de un momento de calma y bienestar con esta mezcla suave y reconfortante, perfecta para acompañarte en tus espacios de descanso...',
    description: 'Disfruta de un momento de calma y bienestar con esta mezcla suave y reconfortante, perfecta para acompañarte en tus espacios de descanso o desconexión. Su sabor cálido y ligeramente dulce crea una experiencia envolvente desde el primer sorbo 🌙\n\n🌿 Elaborado a base de rooibos, una infusión naturalmente libre de cafeína, ideal para cualquier momento del día, incluso en la noche.\n\n🥥 Su mezcla con almendras, coco, pétalos de rosa y vainilla aporta notas delicadas, cremosas y florales que equilibran perfectamente el sabor, creando una bebida armoniosa y agradable.\n\n💛 Beneficios:\n• Relajante, ideal para bajar el ritmo del día\n• Digestivo y suave con el cuerpo\n• Aporta al equilibrio emocional\n• Fuente de antioxidantes, hierro y magnesio\n• No contiene teína\n\n🍃 Ingredientes:\nRooibos, almendras, coco, pétalos de rosa y vainilla\n\n✨ Una infusión pensada para reconectar contigo, bajar el ritmo y disfrutar lo simple.\nI',
    benefits: ['Antioxidante', 'Digestivo', 'Relajante'],
    price: 38000, price_label: '/ 35g',
    image_url: '/productos/te-rooibos-vainilla-35g.jpg',
    images: [],
    tags: ['no-crop', 'natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 11,
  },
  {
    id: 'p-012', slug: 'te-blanco-te-mujer-20g', name: 'Té Blanco - Té Mujer-20g',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Es un té creado para acompañar tus días de luna, cuando el cuerpo pide suavidad, claridad y conexión   Cultivado en los Andes...',
    description: 'Es un té creado para acompañar tus días de luna, cuando el cuerpo pide suavidad, claridad y conexión \n\nCultivado en los Andes Colombianos, este té blanco orgánico ofrece una experiencia delicada, ligera y armoniosa, ideal para esos momentos donde necesitas bajar el ritmo sin desconectarte por completo.\n\nSu perfil suave y elegante ayuda a:\n• aportar antioxidantes al cuerpo\n• brindar energía natural sin sobreestimular\n• promover la salud celular\n• acompañar el equilibrio físico y emocional\n\n🍃 Ingredientes:\nTé blanco orgánico, cardamomo, naranja deshidratada y canela\n\nUn ritual consciente para escucharte, cuidarte y transitar tus ciclos con mayor calma ✨',
    benefits: ['Antioxidante'],
    price: 25000, price_label: '/ 20g',
    image_url: '/productos/te-blanco-te-mujer-20g.jpg',
    images: [],
    tags: ['no-crop', 'natural'],
    is_featured: false, is_available: true, sort_order: 12,
  },
  {
    id: 'p-013', slug: 'te-blanco-te-mujer-35g', name: 'Té Blanco - Té Mujer- 35g',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Es un té creado para acompañar tus días de luna, cuando el cuerpo pide suavidad, claridad y conexión   Cultivado en los Andes...',
    description: 'Es un té creado para acompañar tus días de luna, cuando el cuerpo pide suavidad, claridad y conexión \n\nCultivado en los Andes Colombianos, este té blanco orgánico ofrece una experiencia delicada, ligera y armoniosa, ideal para esos momentos donde necesitas bajar el ritmo sin desconectarte por completo.\n\nSu perfil suave y elegante ayuda a:\n• aportar antioxidantes al cuerpo\n• brindar energía natural sin sobreestimular\n• promover la salud celular\n• acompañar el equilibrio físico y emocional\n\n🍃 Ingredientes:\nTé blanco orgánico, cardamomo, naranja deshidratada y canela\n\nUn ritual consciente para escucharte, cuidarte y transitar tus ciclos con mayor calma ✨',
    benefits: ['Antioxidante'],
    price: 35000, price_label: '/ 35g',
    image_url: '/productos/te-blanco-te-mujer-35g.jpg',
    images: [],
    tags: ['no-crop', 'natural'],
    is_featured: false, is_available: true, sort_order: 13,
  },
  {
    id: 'p-014', slug: 'jabon-para-afeitar-natiu', name: 'Jabón para afeitar - Natiu',
    brand: 'Natiú', category_id: 'cat-6',
    short_desc: 'Transforma tu afeitado con nuestro jabón 100% natural y artesanal.',
    description: 'Transforma tu afeitado con nuestro jabón 100% natural y artesanal. Formulado con manteca de cacao, aceite de coco y ricino, crea una espuma cremosa que protege y calma tu piel, previniendo cortes e irritación. \n\n•Deslizamiento Superior: Evita irritaciones.\n•Hidratación Profunda: Piel suave y sedosa.\n•Natural y Vegano: Libre de químicos sintéticos.\n•Versátil: Ideal para rostro, piernas y axilas.\n•Todo tipo de piel: Perfecto incluso para pieles sensibles.',
    benefits: ['Hidratante'],
    price: 19000, price_label: '',
    image_url: '/productos/jabon-para-afeitar-natiu.jpg',
    images: [],
    tags: ['natural', 'vegano', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 14,
  },
  {
    id: 'p-015', slug: 'desodorante-natural-de-lavanda', name: 'Desodorante Natural de Lavanda',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Sus compuestos naturales contribuyen a refrescar la piel y a mantener una sensación de limpieza prolongada durante el día.',
    description: 'Sus compuestos naturales contribuyen a refrescar la piel y a mantener una sensación de limpieza prolongada durante el día. Además, favorece la oxigenación de los tejidos, lo que le da a la piel un aspecto más uniforme y saludable.\n\nLa lavanda también  tiene propiedades antibacterianas, esto  es clave porque el mal olor no lo produce el sudor en sí, sino las bacterias que poseemos y a diferencia de los desodorantes convencionales, no tapa los poros',
    benefits: ['Natural'],
    price: 27000, price_label: '',
    image_url: '/productos/desodorante-natural-de-lavanda.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 15,
  },
  {
    id: 'p-016', slug: 'aceite-corporal-serenidad', name: 'Aceite Corporal Serenidad',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Una mezcla floral suave creada para equilibrar las emociones y promover una sensación profunda de calma.',
    description: 'Una mezcla floral suave creada para equilibrar las emociones y promover una sensación profunda de calma. Combina lavanda, manzanilla y ylang-ylang, aceites esenciales reconocidos por sus efectos relajantes y armonizantes.\n\nAyuda a disminuir el estrés diario, favorece un mejor estado de ánimo y contribuye al cuidado natural de la piel, apoyando la retención de su hidratación y suavidad.\n\n✨ Ideal para:\n• Momentos de estrés o ansiedad\n• Rutinas de autocuidado y relajación\n• Aromaterapia emocional\n• Masajes relajantes y cuidado de la piel',
    benefits: ['Relajante', 'Hidratante'],
    price: 69000, price_label: '',
    image_url: '/productos/aceite-corporal-serenidad.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 16,
  },
  {
    id: 'p-017', slug: 'jabon-corporal-de-coco-oiris', name: 'Jabón Corporal de Coco - Oiris',
    brand: 'Oiris', category_id: 'cat-5',
    short_desc: 'Jabón artesanal elaborado con alta concentración de aceite de coco y enriquecido con leche de coco, ideal para limpiar y nutrir la piel...',
    description: 'Jabón artesanal elaborado con alta concentración de aceite de coco y enriquecido con leche de coco, ideal para limpiar y nutrir la piel de forma suave y natural.\n\nEl coco, rico en minerales esenciales, ayuda a proteger la piel mientras aporta hidratación profunda y duradera, dejando una sensación suave y saludable.\n\n•Hidratación intensa para piel seca\n•Mejora la elasticidad de la piel\n•Aroma natural y suave\n•Apto para rostro y cuerpo\n•Ideal para uso diario',
    benefits: ['Hidratante'],
    price: 14000, price_label: '',
    image_url: '/productos/jabon-corporal-de-coco-oiris.jpg',
    images: ['/productos/jabon-corporal-de-coco-oiris-g-jabon-de-coco-2.jpg'],
    tags: ['natural', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 17,
  },
  {
    id: 'p-018', slug: 'lima-para-unas-en-vidrio-templado', name: 'Lima para Uñas en Vidrio  templado',
    brand: 'Hooli', category_id: 'cat-3',
    short_desc: 'Lima de cristal de alta calidad, ideal para el cuidado de uñas naturales o acrílicas.',
    description: 'Lima de cristal de alta calidad, ideal para el cuidado de uñas naturales o acrílicas. Diseñada para un limado suave, preciso y duradero, ayudando a cuidar y mantener la forma de tus uñas sin maltratarlas.\n\n•Doble cara de limado\n•Superficie de cristal resistente y duradera\n•Lavable y desinfectable sin perder eficacia\n•Reutilizable por largo tiempo\n\n100% libre de plástico.',
    benefits: ['Natural'],
    price: 25000, price_label: '',
    image_url: '/productos/lima-para-unas-en-vidrio-templado.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 18,
  },
  {
    id: 'p-019', slug: 'removedor-para-unas-libre-de-acetona-humectacion-bnatural', name: 'Removedor para uñas libre de Acetona + Humectación; Bnatural',
    brand: 'Bnatural', category_id: 'cat-3',
    short_desc: 'Retira el esmalte de forma suave y efectiva sin resecar ni debilitar tus uñas   •Libre de acetona y tolueno •Con aceites naturales...',
    description: 'Retira el esmalte de forma suave y efectiva sin resecar ni debilitar tus uñas \n\n•Libre de acetona y tolueno\n•Con aceites naturales humectantes\n•No reseca ni maltrata uñas ni cutículas\n•Ideal para uñas sensibles o frágiles',
    benefits: ['Natural'],
    price: 18000, price_label: '',
    image_url: '/productos/removedor-para-unas-libre-de-acetona-humectacion-bnatural.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 19,
  },
  {
    id: 'p-020', slug: 'aceite-para-barba-naitu', name: 'Aceite para barba - Naitu',
    brand: 'Natiú', category_id: 'cat-6',
    short_desc: 'Aceite de barba 100% natural, elaborado con una cuidadosa mezcla de aceites vegetales nutritivos e hidratantes, ideal para todo tipo y...',
    description: 'Aceite de barba 100% natural, elaborado con una cuidadosa mezcla de aceites vegetales nutritivos e hidratantes, ideal para todo tipo y longitud de barba.\n\nFormulado con aceite de oliva, almendra, coco, argán, aguacate y ricino, ayuda a prevenir la resequedad, estimular el crecimiento y mejorar el brillo, la suavidad y la manejabilidad del vello facial, aportando una apariencia saludable y bien cuidada.',
    benefits: ['Hidratante'],
    price: 30000, price_label: '',
    image_url: '/productos/aceite-para-barba-naitu.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 20,
  },
  {
    id: 'p-021', slug: 'protector-solar-con-extractos-naturales-econativa', name: 'Protector Solar con Extractos Naturales Econativa',
    brand: 'Econativa', category_id: 'cat-5',
    short_desc: 'Protección solar efectiva con ingredientes naturales  Cuida tu piel mientras la protege de los rayos UVA y UVB.',
    description: 'Protección solar efectiva con ingredientes naturales \nCuida tu piel mientras la protege de los rayos UVA y UVB.\n\n•SPF 50 con barrera física protectora\n•Ingredientes naturales y biodegradables\n•Hipoalergénico y libre de parabenos\n•Ideal para pieles sensibles\n•Cruelty free \n\n30 ml',
    benefits: ['Natural'],
    price: 36000, price_label: '',
    image_url: '/productos/protector-solar-con-extractos-naturales-econativa.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'biodegradable'],
    is_featured: true, is_available: true, sort_order: 21,
  },
  {
    id: 'p-022', slug: 'seda-dental-biodegradable-de-maiz-con-envase-de-vidrio', name: 'Seda Dental Biodegradable de Maíz con Envase de Vidrio',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Seda dental ecológica elaborada a base de maíz, una alternativa libre de plástico para el cuidado diario y en un envase de vidrio...',
    description: 'Seda dental ecológica elaborada a base de maíz, una alternativa libre de plástico para el cuidado diario y en un envase de vidrio reutilizable.\nAproximadamente 30 m.',
    benefits: ['Natural'],
    price: 21000, price_label: '',
    image_url: '/productos/seda-dental-biodegradable-de-maiz-con-envase-de-vidrio.jpg',
    images: [],
    tags: ['eco-friendly', 'biodegradable'],
    is_featured: false, is_available: true, sort_order: 22,
  },
  {
    id: 'p-023', slug: 'desodorante-vegano-sin-aluminio-coco-vainilla', name: 'Desodorante Vegano sin Aluminio. Coco-Vainilla',
    brand: 'Hooli', category_id: 'cat-4',
    short_desc: 'Desodorante Sólido de fragancia a Coco-Vainilla.',
    description: 'Desodorante Sólido de fragancia a Coco-Vainilla. Formulado con ingredientes naturales, libre de aluminio y parabenos.\nControla el sudor, elimina malos olores de forma eficaz, sin comprometer tu dualidad ni el medio ambiente',
    benefits: ['Natural'],
    price: 43000, price_label: '',
    image_url: '/productos/desodorante-vegano-sin-aluminio-coco-vainilla.jpg',
    images: ['/productos/desodorante-vegano-sin-aluminio-coco-vainilla-g-sodorante-vainilla-2.jpg'],
    tags: ['natural', 'vegano', 'sin aluminio'],
    is_featured: true, is_available: true, sort_order: 23,
  },
  {
    id: 'p-024', slug: 'shampoo-botanico-bioma-y-clorofila', name: 'Shampoo Botánico Bioma y Clorofila',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Shampoo Bioma ( Hidratación ) elaborado a partir de ingredientes de origen natural cuidadosamente seleccionados.',
    description: 'Shampoo Bioma ( Hidratación )\nelaborado a partir de ingredientes de origen natural cuidadosamente seleccionados. Su fórmula, basada en plantas, nutre el cabello desde la raíz, aportando fuerza, hidratación y brillo visible desde las primeras aplicaciones.\n\nEnriquecido con activos naturales como coco, aguacate, jengibre, lavanda, aloe vera, cebolla y cúrcuma, combinados para cuidar el cabello de manera suave y efectiva, respetando su equilibrio natural\n\n•Shampoo ( Sedosidad y Brillo )\nelaborado con ingredientes de origen natural, inspirado en el poder restaurador de las plantas. La ortiga fortalece el cuero cabelludo y ayuda a revitalizar el cabello desde la raíz, mientras que la miel aporta suavidad y un brillo natural que realza su luminosidad y vitalidad desde las primeras aplicaciones.\n\nSu combinación botánica, enriquecida con romero, ginkgo biloba, aloe vera, aguacate, y café, nutre profundamente el cabello, dejándolo con una apariencia saludable, fuerte y llena de vida.\n\nLibre de sulfatos, parabenos, siliconas y sal.\n\nIdeal para mujeres y hombres con cabello débil, maltratado o con poca densidad. Funciona perfectamente en cabellos lisos, ondulados y rizados, siendo apto para todo tipo de cabello.',
    benefits: ['Hidratante', 'Fortalecedor'],
    price: 39000, price_label: '',
    image_url: '/productos/shampoo-botanico-bioma-y-clorofila.jpg',
    images: ['/productos/shampoo-botanico-bioma-y-clorofila-g-oma-y-acondicionador.jpg'],
    tags: ['natural'],
    is_featured: true, is_available: true, sort_order: 24,
  },
  {
    id: 'p-025', slug: 'roll-on-sana', name: 'Roll on Sana',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceite Esencial “Sana”  Una mezcla botánica creada para brindar alivio y bienestar corporal de forma natural.',
    description: 'Aceite Esencial “Sana”\n\nUna mezcla botánica creada para brindar alivio y bienestar corporal de forma natural. Elaborado con raíz de cúrcuma, vetiver, eucalipto, naranja, ciprés y romero, reconocidos por sus propiedades antiinflamatorias y analgésicas.\n\nSu combinación aromática ayuda a relajar los músculos y aliviar molestias articulares, óseas y musculares, aportando una sensación reconfortante y revitalizante después del esfuerzo físico o la tensión diaria.\n\n✨ Ideal para:\n• Masajes corporales\n• Recuperación muscular\n• Tensiones y fatiga física\n• Momentos de descanso y autocuidado',
    benefits: ['Antiinflamatorio'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-sana.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    image_fit: 'contain',
    image_position: 'center bottom',
    is_featured: false, is_available: true, sort_order: 25,
  },
  {
    id: 'p-026', slug: 'roll-on-descanso', name: 'Roll on Descanso',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceite Esencial “Sana”  Una mezcla botánica creada para brindar alivio y bienestar corporal de forma natural.',
    description: 'Aceite Esencial “Sana”\n\nUna mezcla botánica creada para brindar alivio y bienestar corporal de forma natural. Elaborado con raíz de cúrcuma, vetiver, eucalipto, naranja, ciprés y romero, reconocidos por sus propiedades antiinflamatorias y analgésicas.\n\nSu combinación aromática ayuda a relajar los músculos y aliviar molestias articulares, óseas y musculares, aportando una sensación reconfortante y revitalizante después del esfuerzo físico o la tensión diaria.\n\n✨ Ideal para:\n• Masajes corporales\n• Recuperación muscular\n• Tensiones y fatiga física\n• Momentos de descanso y autocuidado',
    benefits: ['Antiinflamatorio'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-descanso.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    is_featured: true, is_available: true, sort_order: 26,
  },
  {
    id: 'p-027', slug: 'roll-on-energia', name: 'Roll on Energía',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceite Esencial “Energía”  Una mezcla herbal y refrescante diseñada para activar el cuerpo y revitalizar los sentidos.',
    description: 'Aceite Esencial “Energía”\n\nUna mezcla herbal y refrescante diseñada para activar el cuerpo y revitalizar los sentidos. Combina naranja, ciprés y menta, ingredientes conocidos por estimular la digestión y favorecer la circulación.\n\nSu aroma fresco y vibrante ayuda a despertar la energía natural del cuerpo, generando una sensación de activación y ligereza ideal para comenzar el día o recuperar el impulso en momentos de cansancio.\n\n✨ Ideal para:\n• Iniciar el día con vitalidad\n• Estimular la digestión\n• Activar cuerpo y mente\n• Aromaterapia energizante',
    benefits: ['Energizante'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-energia.jpg',
    images: [],
    tags: ['natural', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 27,
  },
  {
    id: 'p-028', slug: 'roll-on-pausa', name: 'Roll on Pausa',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Una mezcla botánica diseñada para brindar alivio y bienestar respiratorio en momentos de congestión o cambios de clima.',
    description: 'Una mezcla botánica diseñada para brindar alivio y bienestar respiratorio en momentos de congestión o cambios de clima. Elaborado con cedro, pino, limonaria, eucalipto, tomillo, árbol de té, romero y rosas, reconocidos por sus propiedades descongestionantes y purificantes.\n\nAyuda a despejar las vías respiratorias y aporta una sensación de alivio y frescura, favoreciendo el cuidado natural frente a gripes, alergias y molestias respiratorias leves.\n\n✨ Ideal para:\n• Momentos de congestión nasal\n• Cambios de clima\n• Rutinas de cuidado respiratorio\n• Relajación y descanso nocturno',
    benefits: ['Natural'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-pausa.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 28,
  },
  {
    id: 'p-029', slug: 'roll-on-serenidad', name: 'Roll on Serenidad',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceite Esencial “Serenidad”  Una mezcla floral suave creada para equilibrar las emociones y promover una sensación profunda de calma.',
    description: 'Aceite Esencial “Serenidad”\n\nUna mezcla floral suave creada para equilibrar las emociones y promover una sensación profunda de calma. Combina lavanda, ylang-ylang y manzanilla; aceites esenciales reconocidos por sus efectos relajantes y armonizantes.\n\nAyuda a disminuir el estrés diario, favorece un mejor estado de ánimo y contribuye al cuidado natural de la piel, apoyando la retención de su hidratación y suavidad.\n\n✨ Ideal para:\n• Momentos de estrés o ansiedad\n• Rutinas de autocuidado y relajación\n• Aromaterapia emocional\n• Masajes relajantes y cuidado de la piel',
    benefits: ['Relajante', 'Hidratante'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-serenidad.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 29,
  },
  {
    id: 'p-030', slug: 'roll-on-lavanda', name: 'Roll on Lavanda',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceite Esencial de Lavanda  Un clásico de la aromaterapia reconocido por su versatilidad y equilibrio natural.',
    description: 'Aceite Esencial de Lavanda\n\nUn clásico de la aromaterapia reconocido por su versatilidad y equilibrio natural. La lavanda aporta propiedades cicatrizantes y antiinflamatorias que ayudan a cuidar la piel mientras su aroma suave promueve relajación y bienestar emocional.\n\nContribuye a aliviar el estrés y la ansiedad, favorece la relajación muscular y apoya la hidratación natural del cuero cabelludo. Además, sus propiedades antimicrobianas y su efecto repelente suave lo convierten en un aliado ideal para el cuidado diario.\n\n✨ Ideal para:\n• Relajación y descanso\n• Cuidado de piel y cuero cabelludo\n• Masajes relajantes\n• Aromaterapia diaria\n• Repelente natural suave',
    benefits: ['Relajante', 'Hidratante', 'Antiinflamatorio', 'Cicatrizante'],
    price: 26000, price_label: '',
    image_url: '/productos/roll-on-lavanda.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 30,
  },
  {
    id: 'p-031', slug: 'agua-de-rosas', name: 'Agua de Rosas',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Un tónico facial natural que hidrata, equilibra y revitaliza la piel diariamente.',
    description: 'Un tónico facial natural que hidrata, equilibra y revitaliza la piel diariamente. El agua de rosas es reconocida por sus propiedades hidratantes, antiinflamatorias y antibacterianas, ayudando a mantener el rostro fresco y saludable.\n\nContribuye a equilibrar el pH de la piel, reducir la aparición de acné y minimizar la apariencia de los poros, dejando una sensación suave y luminosa. También funciona como desmaquillante ligero y fijador natural para refrescar la piel durante el día.\n\n✨ Ideal para:\n• Hidratación diaria del rostro\n• Equilibrar el pH de la piel\n• Piel con tendencia al acné\n• Refrescar y suavizar la piel\n• Fijar y revitalizar el maquillaje',
    benefits: ['Hidratante', 'Antiinflamatorio'],
    price: 19000, price_label: '',
    image_url: '/productos/agua-de-rosas.jpg',
    images: [],
    tags: ['natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 31,
  },
  {
    id: 'p-032', slug: 'acondicionador-botanico-brisa', name: 'Acondicionador Botánico Brisa',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Un cuidado nutritivo diseñado para dejar el cabello suave, ligero y lleno de vida.',
    description: 'Un cuidado nutritivo diseñado para dejar el cabello suave, ligero y lleno de vida. Formulado con lavanda, aguacate, coco, vitamina E y proteína de seda, ingredientes que ayudan a restaurar la hidratación y fortalecer la fibra capilar.\n\nAporta mayor suavidad y elasticidad al cabello, disminuyendo la rotura y controlando el frizz, mientras deja una sensación sedosa y manejable desde la primera aplicación.\n\n✨ Ideal para:\n• Cabello seco o maltratado\n• Reducir frizz y enredos\n• Aumentar suavidad y brillo\n• Mejorar la elasticidad capilar\n• Nutrición e hidratación diaria',
    benefits: ['Hidratante', 'Fortalecedor'],
    price: 39000, price_label: '',
    image_url: '/productos/acondicionador-botanico-brisa.jpg',
    images: [],
    tags: ['no-crop', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 32,
  },
  {
    id: 'p-033', slug: 'cepillo-dental-de-bambu', name: 'Cepillo Dental de Bambú',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Una alternativa consciente para el cuidado diario y el bienestar del planeta.',
    description: 'Una alternativa consciente para el cuidado diario y el bienestar del planeta. Elaborado con mango de bambú natural, ligero y resistente, diseñado para una limpieza efectiva mientras reduces el uso de plásticos en tu rutina.\n\nSus cerdas permiten una limpieza suave y profunda, cuidando dientes y encías sin generar agresión, ideal para el uso diario.\n\n✨ Características:\n• Mango de bambú natural y biodegradable\n• Ligero, resistente y cómodo de usar\n• Limpieza suave y efectiva\n• Alternativa ecológica al cepillo tradicional\n• Diseño minimalista y sostenible',
    benefits: ['Natural'],
    price: 7000, price_label: '',
    image_url: '/productos/cepillo-dental-de-bambu.jpg',
    images: [],
    tags: ['no-crop', 'natural', 'eco-friendly', 'bambú', 'biodegradable'],
    is_featured: false, is_available: true, sort_order: 33,
  },
  {
    id: 'p-034', slug: 'tetera-de-vidrio-con-mango-de-madera', name: 'Tetera de Vidrio con Mango de Madera',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Una tetera diseñada para convertir cada preparación en un ritual especial.',
    description: 'Una tetera diseñada para convertir cada preparación en un ritual especial. Elaborada en vidrio resistente al calor, incorpora un infusor de vidrio removible que permite preparar infusiones de forma limpia, conservando el sabor y la pureza natural de las hierbas.\n\nSu mango de madera aporta un toque cálido y artesanal, brindando comodidad y seguridad al servir.\n\n✨ Características:\n• Vidrio resistente a altas temperaturas\n• Infusor de vidrio removible\n• Mango de madera ergonómico\n• Preparación natural y elegante\n• Fácil limpieza y uso diario\n\n🌿 Ideal para disfrutar tés e infusiones en momentos de calma y bienestar.',
    benefits: ['Natural'],
    price: 69000, price_label: '',
    image_url: '/productos/tetera-de-vidrio-con-mango-de-madera.jpg',
    images: [],
    tags: ['natural', 'artesanal'],
    is_featured: true, is_available: true, sort_order: 34,
  },
  {
    id: 'p-035', slug: 'tetera-de-vidrio-con-infusor', name: 'Tetera de Vidrio con Infusor',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Diseñada para transformar cada infusión en un pequeño ritual.',
    description: 'Diseñada para transformar cada infusión en un pequeño ritual. Esta tetera de vidrio cuenta con infusor interno de acero inoxidable, ideal para preparar tés e infusiones de manera práctica y limpia.\n\nFabricada en vidrio resistente a altas temperaturas, permite observar el proceso de preparación mientras conserva el sabor y aroma natural de las hierbas. Su tapa ajustable brinda seguridad y comodidad al servir.\n\n✨ Características:\n• Vidrio resistente al calor\n• Infusor interno de acero inoxidable\n• Tapa ajustable y segura\n• Ideal para tés e infusiones naturales\n• Fácil de limpiar y reutilizable\n\n🌿 Perfecta para rituales de té, momentos de pausa y bienestar diario.',
    benefits: ['Natural'],
    price: 44500, price_label: '',
    image_url: '/productos/tetera-de-vidrio-con-infusor.jpg',
    images: [],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 35,
  },
  {
    id: 'p-036', slug: 'pomada-de-hierbas-y-calendula', name: 'Pomada de Hierbas y Caléndula',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'omada de Hierbas  Una fórmula natural pensada para brindar alivio y bienestar en momentos de malestar.',
    description: 'omada de Hierbas\n\nUna fórmula natural pensada para brindar alivio y bienestar en momentos de malestar. Su mezcla herbal ayuda a desinflamar y reconfortar el cuerpo, siendo un apoyo ideal durante resfriados o cambios de clima.\n\nAporta una sensación calmante y reconfortante que favorece el descanso y el cuidado natural.\n\n✨ Ideal para:\n• Resfriados y congestión\n• Masajes reconfortantes\n• Aliviar molestias corporales\n• Cuidado natural diario\n\n🌱 Aplicar mediante masaje suave en pecho, espalda o zonas necesarias.\n\n⸻\n\n🌼 Pomada de Caléndula\n\nUn cuidado suave y reparador para la piel. La caléndula es reconocida por sus propiedades antiinflamatorias, cicatrizantes y antisépticas, ayudando a proteger y regenerar la piel de forma natural.\n\nIdeal para calmar irritaciones, resequedad o pequeñas molestias cutáneas, dejando la piel más suave y equilibrada.\n\n✨ Ideal para:\n• Piel irritada o sensible\n• Regeneración y cuidado cutáneo\n• Resequedad o enrojecimiento\n• Uso diario en piel delicada\n\n🌱 Aplicar una pequeña cantidad sobre la zona limpia y masajear suavemente.',
    benefits: ['Antiinflamatorio', 'Cicatrizante'],
    price: 36000, price_label: '',
    image_url: '/productos/pomada-de-hierbas-y-calendula.jpg',
    images: [],
    tags: ['natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 36,
  },
  {
    id: 'p-037', slug: 'velas-de-cera-vegetal', name: 'Velas de Cera Vegetal',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Vela Aromática “Energía”  Una vela diseñada para activar los sentidos y llenar tus espacios de vitalidad.',
    description: 'Vela Aromática “Energía”\n\nUna vela diseñada para activar los sentidos y llenar tus espacios de vitalidad. Su aroma frutal crea una atmósfera fresca y estimulante, ideal para acompañar momentos de inspiración y movimiento.\n\nEl pabilo de madera produce un suave crepitar al encenderse, generando una experiencia cálida y envolvente que transforma cualquier ambiente.\n\n✨ Ideal para:\n• Activar la energía del espacio\n• Momentos creativos o de trabajo\n• Aromatizar naturalmente el hogar\n• Crear ambientes vibrantes y positivos\n\n🌿 Aroma frutal \n\n⸻\n\n🌿 Vela Aromática “Calma”\n\nUna vela creada para invitar a la tranquilidad y el descanso. Su aroma herbal con notas de romero aporta una sensación fresca y equilibrante, perfecta para desacelerar después del día.\n\nEl pabilo de madera añade un suave sonido relajante que acompaña momentos de pausa, meditación o descanso.\n\n✨ Ideal para:\n• Relajación y descanso\n• Meditación o lectura\n• Crear ambientes serenos\n• Rituales de autocuidado\n\n🌿 Aroma herbal con romero',
    benefits: ['Relajante'],
    price: 25000, price_label: '',
    image_url: '/productos/velas-de-cera-vegetal.jpg',
    images: [],
    tags: ['natural'],
    is_featured: true, is_available: true, sort_order: 37,
  },
  {
    id: 'p-038', slug: 'agua-de-romero', name: 'Agua de Romero',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Un tónico capilar natural que fortalece y revitaliza el cuero cabelludo.',
    description: 'Un tónico capilar natural que fortalece y revitaliza el cuero cabelludo. El romero es reconocido por sus propiedades astringentes, antisépticas, antioxidantes y tonificantes, ideales para el cuidado diario del cabello.\n\nAyuda a estimular el crecimiento capilar, reducir la caída y regular la producción de grasa en el cuero cabelludo, aportando una sensación de frescura mientras mejora el brillo y la suavidad del cabello.\n\n✨ Ideal para:\n• Fortalecer el cabello\n• Estimular el crecimiento capilar\n• Regular cuero cabelludo graso\n• Aportar brillo y suavidad natural\n• Refrescar y tonificar el cuero cabelludo',
    benefits: ['Antioxidante', 'Fortalecedor'],
    price: 19000, price_label: '',
    image_url: '/productos/agua-de-romero.jpg',
    images: [],
    tags: ['natural', 'eco-friendly'],
    is_featured: false, is_available: true, sort_order: 38,
  },
  {
    id: 'p-039', slug: 'jabon-corporal-de-sal-rosada-del-himalaya', name: 'Jabón Corporal de Sal rosada del Himalaya',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Jabón artesanal diseñado para exfoliar suavemente, estimular la regeneración celular y mejorar visiblemente la textura de la piel, ideal...',
    description: 'Jabón artesanal diseñado para exfoliar suavemente, estimular la regeneración celular y mejorar visiblemente la textura de la piel, ideal para uso diario.\n\nGracias a sus partículas cristalinas naturales, ayuda a eliminar impurezas, células muertas y exceso de grasa, dejando la piel más suave, luminosa y renovada. Su acción sinérgica limpia profundamente sin resecar, respetando el equilibrio natural de la piel.\n\n•Exfoliación suave y efectiva\n•Estimula la renovación celular\n•Mejora la textura y luminosidad de la piel\n•Limpieza profunda sin resecar\n•Apto para uso diario en rostro y cuerpo',
    benefits: ['Natural'],
    price: 22000, price_label: '',
    image_url: '/productos/jabon-corporal-de-sal-rosada-del-himalaya.jpg',
    images: [],
    tags: ['natural', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 39,
  },
  {
    id: 'p-040', slug: 'crema-hidratante-en-barra-hooli', name: 'Crema Hidratante en Barra- Hoolí',
    brand: 'Hooli', category_id: 'cat-5',
    short_desc: 'Crema corporal en barra de naranja, elaborada con manteca de cacao y aceite jojoba, ofrece una hidratación profunda y nutritiva,...',
    description: 'Crema corporal en barra de naranja, elaborada con manteca de cacao y aceite jojoba, ofrece una hidratación profunda y nutritiva, perfecta para todo tipo de piel.\n\nElaborada con ingredientes completamente naturales y veganos, sin parabenos ni químicos agresivos \n\nOpción perfecta para llevar en tus viajes',
    benefits: ['Hidratante', 'Sin parabenos'],
    price: 39900, price_label: '',
    image_url: '/productos/crema-hidratante-en-barra-hooli.jpg',
    images: ['/productos/crema-hidratante-en-barra-hooli-g-n-barra-hidratante-2.jpg', '/productos/crema-hidratante-en-barra-hooli-g-n-barra-hidratante-4.jpg'],
    tags: ['natural', 'vegano', 'sin parabenos'],
    is_featured: false, is_available: true, sort_order: 40,
  },
  {
    id: 'p-041', slug: 'jabon-corporal-de-miel-y-leche-de-almendras', name: 'Jabón Corporal de Miel y Leche de Almendras',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Jabón artesanal sostenible y natural libre sulfatos, fragancias artificiales, colorantes y productos de origen animal, ideal para pieles...',
    description: 'Jabón artesanal sostenible y natural libre sulfatos, fragancias artificiales, colorantes y productos de origen animal, ideal para pieles sensibles gracias a su fórmula suave, hipoalergénica y profundamente hidratante.\nLa miel y la leche de almendras restaúran la barrera de humedad natural de la piel, dejándola suave y flexible',
    benefits: ['Hidratante'],
    price: 22000, price_label: '',
    image_url: '/productos/jabon-corporal-de-miel-y-leche-de-almendras.jpg',
    images: ['/productos/jabon-corporal-de-miel-y-leche-de-almendras-g-on-de-miel-almendras.jpg', '/productos/jabon-corporal-de-miel-y-leche-de-almendras-g--de-miel-almendras-2.jpg'],
    tags: ['natural', 'artesanal', 'snack'],
    is_featured: true, is_available: true, sort_order: 41,
  },
  {
    id: 'p-042', slug: 'balsamo-labial-de-menta-hooli', name: 'Bálsamo labial de Menta - Hoolí',
    brand: 'Hooli', category_id: 'cat-4',
    short_desc: 'Hidratación intensiva y reparación profunda para labios secos o agrietados.',
    description: 'Hidratación intensiva y reparación profunda para labios secos o agrietados. Fórmula vegetal, biodegradable y amigable con el medio ambiente. Proporciona una textura suave  y protección contra el clima extremo. \n\n•Beneficios: Repara, suaviza, protege.\nFórmula: 100% Natural, Vegan, Eco-friendly',
    benefits: ['Hidratante'],
    price: 27000, price_label: '',
    image_url: '/productos/balsamo-labial-de-menta-hooli.jpg',
    images: ['/productos/balsamo-labial-de-menta-hooli-g-mo-labial-de-menta-2.jpg'],
    tags: ['natural', 'eco-friendly', 'biodegradable'],
    is_featured: false, is_available: true, sort_order: 42,
  },
  {
    id: 'p-043', slug: 'crema-dental-sin-fluor-en-pastillas-oiris', name: 'Crema dental sin flúor en pastillas - Oiris',
    brand: 'Oiris', category_id: 'cat-4',
    short_desc: 'Es una alternativa ecológica, vegana y 100% natural (sin flúor ni conservantes) diseñada para un estilo de vida cero residuos.',
    description: 'Es una alternativa ecológica, vegana y 100% natural (sin flúor ni conservantes) diseñada para un estilo de vida cero residuos. Su fórmula sólida de arcilla blanca y carbonato de calcio limpia profundamente respetando el esmalte, mientras que el aceite de coco reduce la placa y la menta piperita aporta frescura intensa. Es práctica, fácil de usar y sin desperdicios. \n•Eco-friendly: Vegana y sin empaques plásticos tradicionales.\n•Ingredientes Naturales: Arcilla blanca, carbonato de calcio, coco y menta.\n•Beneficios: Limpieza eficaz, reducción de placa y aliento fresco.\n•Formato: Pastillas sólidas prácticas y sin desperdicios.\n\n120 pastillas \n\n*Modo de uso*\n\nColoca una pastilla en la boca y mastica hasta formar una espuma ligera.\nCepilla como de costumbre con un cepillo húmedo.\nEnjuaga con agua.\nUsar 2 veces al día como parte de tu rutina de higiene bucal.',
    benefits: ['Natural'],
    price: 32000, price_label: '',
    image_url: '/productos/crema-dental-sin-fluor-en-pastillas-oiris.jpg',
    images: [],
    tags: ['natural', 'eco-friendly', 'sin flúor'],
    is_featured: false, is_available: true, sort_order: 43,
  },
  {
    id: 'p-044', slug: 'balsamo-labial-100-natural-con-color-fresa', name: 'Bálsamo labial 100% natural con color fresa',
    brand: 'Hooli', category_id: 'cat-4',
    short_desc: 'Bálsamo labial 100% natural y vegano, diseñado para hidratar, reparar y proteger tus labios mientras aporta un toque suave de color...',
    description: 'Bálsamo labial 100% natural y vegano, diseñado para hidratar, reparar y proteger tus labios mientras aporta un toque suave de color fresa que realza su belleza natural.\n\nSu fórmula nutritiva ayuda a aliviar labios secos o agrietados, creando una barrera protectora frente a cambios climáticos y factores ambientales, manteniéndolos suaves y saludables.\n\n•Hidrata y repara labios resecos\n•Protege contra el frío y el clima\n•Aporta color natural y ligero\n•Ingredientes naturales y veganos\n•Empaque biodegradable y compostable',
    benefits: ['Natural'],
    price: 27000, price_label: '',
    image_url: '/productos/balsamo-labial-100-natural-con-color-fresa.jpg',
    images: ['/productos/balsamo-labial-100-natural-con-color-fresa-g-mo-labial-de-fresa-3.jpg'],
    tags: ['natural', 'vegano', 'eco-friendly', 'biodegradable'],
    is_featured: false, is_available: true, sort_order: 44,
  },
  {
    id: 'p-045', slug: 'jabon-intimo-natural-oiris', name: 'Jabón Íntimo Natural- Oiris',
    brand: 'Oiris', category_id: 'cat-5',
    short_desc: 'Jabón íntimo artesanal elaborado a mano con ingredientes naturales, formulado para limpiar suavemente sin alterar el pH ni la flora vaginal.',
    description: 'Jabón íntimo artesanal elaborado a mano con ingredientes naturales, formulado para limpiar suavemente sin alterar el pH ni la flora vaginal.\n\nSus aceites cuidadosamente seleccionados brindan una sensación de frescura, limpieza y bienestar, respetando el equilibrio natural de la zona íntima.\n\n•Limpieza suave y delicada\n•Respeta el pH íntimo natural\n•Ayuda a mantener el equilibrio de la flora vaginal\n•Sensación de frescura y confort\n•Apto para uso diario',
    benefits: ['Natural'],
    price: 18000, price_label: '',
    image_url: '/productos/jabon-intimo-natural-oiris.jpg',
    images: ['/productos/jabon-intimo-natural-oiris-g-jabon-intimo-2.jpg'],
    tags: ['natural', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 45,
  },
  {
    id: 'p-046', slug: 'jabon-corporal-de-aloe-vera-oiris', name: 'Jabón Corporal de Aloe Vera - Oiris',
    brand: 'Oiris', category_id: 'cat-5',
    short_desc: 'Jabón artesanal elaborado con alto contenido de jugo puro de Aloe Vera, diseñado para calmar, suavizar y regenerar la piel de manera...',
    description: 'Jabón artesanal elaborado con alto contenido de jugo puro de Aloe Vera, diseñado para calmar, suavizar y regenerar la piel de manera natural.\n\nGracias a sus propiedades reparadoras, ayuda a reducir la inflamación, aliviar quemaduras solares y calmar irritaciones o alergias, favoreciendo la regeneración celular.\n\n•Calma y refresca la piel sensible\n•Ayuda a aliviar irritaciones y enrojecimiento\n•Ideal para piel con dermatitis\n•Favorece la regeneración natural de la piel\n•Apto para uso diario en rostro y cuerpo',
    benefits: ['Natural'],
    price: 14000, price_label: '',
    image_url: '/productos/jabon-corporal-de-aloe-vera-oiris.jpg',
    images: ['/productos/jabon-corporal-de-aloe-vera-oiris-g-jabon-de-aloe-vera.jpg', '/productos/jabon-corporal-de-aloe-vera-oiris-g-jabon-de-aloe-vera-2.jpg'],
    tags: ['natural', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 46,
  },
  {
    id: 'p-047', slug: 'base-para-fortalecer-las-unas-bnatural', name: 'Base para fortalecer las uñas Bnatural',
    brand: 'Bnatural', category_id: 'cat-3',
    short_desc: 'Fórmula 21 FREE, libre de químicos agresivos.',
    description: 'Fórmula 21 FREE, libre de químicos agresivos.\nFortalece uñas débiles y quebradizas.\nNo testeado en animales.\n\n12 ml',
    benefits: ['Fortalecedor'],
    price: 16500, price_label: '',
    image_url: '/productos/base-para-fortalecer-las-unas-bnatural.jpg',
    images: ['/productos/base-para-fortalecer-las-unas-bnatural-g-base-para-unas-2.jpg'],
    tags: ['natural'],
    is_featured: false, is_available: true, sort_order: 47,
  },

  // ─── LEGADO — productos anteriores no confirmados en catálogo nuevo ───
  {
    id: 'p-legacy-01', slug: 'blend-te-blanco-citrico', name: 'Blend Té Blanco Cítrico',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Antioxidante y digestivo. Ideal para el equilibrio hormonal.',
    description: 'Una mezcla especial de té blanco orgánico con naranja deshidratada, canela y cardamomo. Antioxidante, digestivo, ayuda al equilibrio hormonal y alivia los cólicos menstruales.',
    ingredients: 'Té blanco orgánico, naranja deshidratada, canela y cardamomo.',
    benefits: ['Antioxidante', 'Digestivo', 'Equilibrio hormonal', 'Alivia cólicos'],
    price: 25000, price_label: '/ 20gr',
    image_url: '/productos/tes-blends.jpg',
    tags: ['orgánico', 'sin teína', 'bienestar femenino'],
    is_featured: false, is_available: false, sort_order: 900,
  },
  {
    id: 'p-legacy-02', slug: 'blend-ashwagandha', name: 'Blend Ashwagandha',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Relajante y digestivo. Sin teína, rico en antioxidantes.',
    description: 'Rooibos con Ashwagandha, canela, cardamomo y jengibre. Relajante y digestivo. No contiene teína. Fuente de antioxidantes, hierro y magnesio.',
    ingredients: 'Rooibos, Ashwagandha, canela, cardamomo y jengibre.',
    benefits: ['Relajante', 'Digestivo', 'Sin teína', 'Antioxidante'],
    price: 0, price_label: '',
    image_url: '/productos/tes-blends.jpg',
    tags: ['adaptógeno', 'sin teína', 'antiestrés'],
    is_featured: false, is_available: false, sort_order: 901,
  },
  {
    id: 'p-legacy-03', slug: 'rooibos-vainilla-coco-rosas', name: 'Rooibos Vainilla Coco-Rosas',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Infusión aromática de rooibos con vainilla, coco y pétalos de rosa.',
    description: 'Planta originaria de Sudáfrica. Contiene hierro y magnesio. Mejora la digestión y regula el estrés. Una experiencia sensorial única.',
    ingredients: 'Rooibos, almendras, coco, pétalos de rosa, vainilla.',
    benefits: ['Sin teína', 'Rico en hierro', 'Digestivo', 'Antiestrés'],
    price: 25000, price_label: '/ 20gr',
    image_url: '/productos/tes-blends.jpg',
    tags: ['sin teína', 'floral', 'reconfortante'],
    is_featured: false, is_available: false, sort_order: 902,
  },
  {
    id: 'p-legacy-04', slug: 'balsamo-huellitas-uma', name: 'Bálsamo Huellitas UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Para las patitas de tus mascotas. Hidrata y protege.',
    description: 'Bálsamo natural especialmente formulado para las patitas de tus mascotas. Hidrata, nutre y protege con ingredientes 100% naturales.',
    ingredients: 'Aceite de coco, manteca de karité y manteca de cacao.',
    benefits: ['Para mascotas', 'Hidratante', 'Protector', '100% natural'],
    price: 27000, price_label: '/ 15gr',
    image_url: '/productos/balsamo-huellitas.jpg',
    tags: ['mascotas', 'natural', 'vegano'],
    is_featured: false, is_available: false, sort_order: 903,
  },
];

export const brandConfig = {
  whatsapp_number: '',
  hero_tagline: 'Lo que le das a tu cuerpo, se lo das al mundo.',
  hero_subtitle: 'Productos naturales, biocosmética y snacks conscientes para una vida más plena.',
  instagram_url: '',
  footer_text: 'UMA Mercado Consciente — Cuidamos de ti y del planeta.',
  meta_description: 'UMA Mercado Consciente — Catálogo de biocosmética, productos eco-amigables, cuidado personal y snacks saludables. Pedidos por WhatsApp.',
};

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const cat = categories.find(c => c.slug === categorySlug);
  if (!cat) return products.filter(p => p.is_available);
  return products.filter(p => p.category_id === cat.id && p.is_available);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.is_featured && p.is_available);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find(c => c.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(p =>
    p.is_available && (
      p.name.toLowerCase().includes(q) ||
      p.short_desc.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q)) ||
      p.benefits.some(b => b.toLowerCase().includes(q))
    )
  );
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function generateWhatsAppUrl(product: Product, waNumber: string): string {
  const number = waNumber.replace(/\D/g, '') || '0000000000';
  const msg = `Hola UMA. Quisiera pedir: *${product.name}* — ${formatPrice(product.price)}${product.price_label || ''}. ¿Pueden confirmarme disponibilidad?`;
  return `https://wa.me/${number}?text=${encodeURIComponent(msg)}`;
}
