import { Category, Product } from '@/types';

export const categories: Category[] = [
  { id: 'cat-1', name: 'Infusiones y Tés', slug: 'infusiones-y-tes', icon: '', sort_order: 1, description: 'Blends herbales para el bienestar y el equilibrio' },
  { id: 'cat-2', name: 'Cuidado Capilar', slug: 'cuidado-capilar', icon: '', sort_order: 2, description: 'Tratamientos naturales para tu cabello' },
  { id: 'cat-3', name: 'Cuidado de Uñas', slug: 'cuidado-de-unas', icon: '', sort_order: 3, description: 'Productos libres de tóxicos para tus manos' },
  { id: 'cat-4', name: 'Higiene Personal', slug: 'higiene-personal', icon: '', sort_order: 4, description: 'Rutina diaria con ingredientes conscientes' },
  { id: 'cat-5', name: 'Cuidado Corporal', slug: 'cuidado-corporal', icon: '', sort_order: 5, description: 'Nutre tu piel con lo mejor de la naturaleza' },
  { id: 'cat-6', name: 'Cuidado para Él', slug: 'cuidado-para-el', icon: '', sort_order: 6, description: 'Grooming natural y consciente' },
  { id: 'cat-7', name: 'Snacks y Bienestar', slug: 'snacks-y-bienestar', icon: '', sort_order: 7, description: 'Alimentos naturales y productos de bienestar' },
];

export const products: Product[] = [
  // ─── INFUSIONES Y TÉS ────────────────────────────────
  {
    id: 'p-01', slug: 'blend-te-blanco-citrico', name: 'Blend Té Blanco Cítrico',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Antioxidante y digestivo. Ideal para el equilibrio hormonal.',
    description: 'Una mezcla especial de té blanco orgánico con naranja deshidratada, canela y cardamomo. Antioxidante, digestivo, ayuda al equilibrio hormonal y alivia los cólicos menstruales.',
    ingredients: 'Té blanco orgánico, naranja deshidratada, canela y cardamomo.',
    benefits: ['Antioxidante', 'Digestivo', 'Equilibrio hormonal', 'Alivia cólicos'],
    price: 25000, price_label: '/ 20gr',
    image_url: '/productos/tes-blends.jpg',
    tags: ['orgánico', 'sin teína', 'bienestar femenino'],
    is_featured: true, is_available: true, sort_order: 1,
  },
  {
    id: 'p-02', slug: 'blend-ashwagandha', name: 'Blend Ashwagandha',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Relajante y digestivo. Sin teína, rico en antioxidantes.',
    description: 'Rooibos con Ashwagandha, canela, cardamomo y jengibre. Relajante y digestivo. No contiene teína. Fuente de antioxidantes, hierro y magnesio.',
    ingredients: 'Rooibos, Ashwagandha, canela, cardamomo y jengibre.',
    benefits: ['Relajante', 'Digestivo', 'Sin teína', 'Antioxidante', 'Hierro y magnesio'],
    price: 29000, price_label: '/ 20gr',
    image_url: '/productos/tes-blends.jpg',
    tags: ['adaptógeno', 'sin teína', 'antiestrés'],
    is_featured: false, is_available: true, sort_order: 2,
  },
  {
    id: 'p-03', slug: 'rooibos-vainilla-coco-rosas', name: 'Rooibos Vainilla Coco-Rosas',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Infusión aromática de rooibos con vainilla, coco y pétalos de rosa.',
    description: 'Planta originaria de Sudáfrica. Contiene hierro y magnesio. Mejora la digestión y regula el estrés. Una experiencia sensorial única.',
    ingredients: 'Rooibos, almendras, coco, pétalos de rosa, vainilla.',
    benefits: ['Sin teína', 'Rico en hierro', 'Digestivo', 'Antiestrés'],
    price: 25000, price_label: '/ 20gr',
    image_url: '/productos/tes-blends.jpg',
    tags: ['sin teína', 'floral', 'reconfortante'],
    is_featured: false, is_available: true, sort_order: 3,
  },
  {
    id: 'p-04', slug: 'tetera-vidrio-mango-madera', name: 'Tetera de Vidrio con Mango de Madera',
    brand: 'UMA', category_id: 'cat-1',
    short_desc: 'Tetera de vidrio resistente al calor con infusor removible.',
    description: 'Tetera elaborada en vidrio resistente al calor, incorpora un infusor de vidrio removible que permite preparar infusiones de forma limpia, conservando el sabor y la pureza natural de las hierbas.',
    benefits: ['Vidrio resistente al calor', 'Infusor removible', 'Sin plásticos'],
    price: 69900, price_label: '',
    image_url: '/productos/tes-blends.jpg',
    tags: ['eco-friendly', 'vidrio', 'sin plástico'],
    is_featured: true, is_available: true, sort_order: 4,
  },
  // ─── CUIDADO CAPILAR ─────────────────────────────────
  {
    id: 'p-05', slug: 'shampoo-bioma-uma', name: 'Shampoo Bioma UMA',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Sin sulfatos ni parabenos. Fórmula botánica para todo tipo de cabello.',
    description: 'Shampoo botánico formulado con ingredientes naturales que respetan el bioma del cuero cabelludo. Sin sulfatos, sin parabenos. Para todo tipo de cabello.',
    ingredients: 'Coco, aguacate, jengibre, lavanda, aloe vera, cebolla, cúrcuma, vitamina E y avena.',
    benefits: ['Sin sulfatos', 'Sin parabenos', 'Nutre el cuero cabelludo', 'Todo tipo de cabello'],
    price: 39000, price_label: '/ 250ml',
    image_url: '/productos/shampoo-bioma.jpg',
    tags: ['sin sulfatos', 'sin parabenos', 'natural', 'vegano'],
    is_featured: true, is_available: true, sort_order: 5,
  },
  {
    id: 'p-06', slug: 'shampoo-clorofila-uma', name: 'Shampoo Clorofila UMA',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Estimulante y purificador con romero, ginkgo biloba y clorofila.',
    description: 'Shampoo enriquecido con clorofila, romero y ginkgo biloba. Estimula la circulación del cuero cabelludo, fortalece el cabello y le aporta brillo. Sin sulfatos, sin parabenos.',
    ingredients: 'Romero, ginkgo biloba, aloe vera, aguacate, cebolla, café, ortiga y miel.',
    benefits: ['Sin sulfatos', 'Sin parabenos', 'Estimula el crecimiento', 'Aporta brillo'],
    price: 39000, price_label: '/ 250ml',
    image_url: '/productos/shampoo-bioma.jpg',
    tags: ['sin sulfatos', 'sin parabenos', 'anticaída', 'natural'],
    is_featured: false, is_available: true, sort_order: 6,
  },
  {
    id: 'p-07', slug: 'acondicionador-botanico-brisa-uma', name: 'Acondicionador Botánico Brisa UMA',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Sin siliconas, sin sal. Hidrata y define sin residuos.',
    description: 'Acondicionador botánico formulado con manteca de karité, lavanda y aceites vegetales nutritivos. Sin siliconas, sin sal. Ideal para todo tipo de cabello.',
    ingredients: 'Manteca de karité, lavanda, coco, aguacate y vitamina E.',
    benefits: ['Sin siliconas', 'Sin sal', 'Hidratación profunda', 'Reduce el frizz'],
    price: 39000, price_label: '/ 250ml',
    image_url: '/productos/acondicionador-brisa.jpg',
    tags: ['sin siliconas', 'sin sal', 'vegano', 'natural'],
    is_featured: false, is_available: true, sort_order: 7,
  },
  {
    id: 'p-08', slug: 'agua-de-romero-natural-uma', name: 'Agua de Romero Natural UMA',
    brand: 'UMA', category_id: 'cat-2',
    short_desc: 'Astringente natural que estimula el crecimiento y reduce la caída.',
    description: 'Es un astringente natural, antiséptico, antioxidante y tonificante. Estimula el crecimiento del cabello, reduce la caída y regula la producción de grasa en el cuero cabelludo. Aporta brillo y suavidad.',
    ingredients: 'Agua destilada de romero 100% natural.',
    benefits: ['Estimula el crecimiento', 'Reduce la caída', 'Regula la grasa', 'Aporta brillo', 'Antioxidante'],
    price: 19000, price_label: '/ 50ml',
    image_url: '/productos/agua-de-romero.jpg',
    tags: ['natural', '100% botánico', 'anticaída'],
    is_featured: false, is_available: true, sort_order: 8,
  },
  // ─── CUIDADO DE UÑAS ─────────────────────────────────
  {
    id: 'p-09', slug: 'base-fortalecer-unas-bnatural', name: 'Base Para Fortalecer Las Uñas Bnatural',
    brand: 'Bnatural', category_id: 'cat-3',
    short_desc: 'Libre de 20 tóxicos. Fortalece sin dañar.',
    description: 'Base fortalecedora de uñas libre de los 20 ingredientes más dañinos: tolueno, benzeno, xileno, formaldehído, ftalatos, siliconas, fragancias sintéticas, derivados animales y más.',
    ingredients: 'Fórmula libre de tóxicos. Sin tolueno, benzeno, xileno, formaldehído ni ftalatos.',
    benefits: ['Libre 20 tóxicos', 'Fortalece las uñas', 'Sin derivados animales', 'Cruelty free'],
    price: 15900, price_label: '',
    image_url: '/productos/base-unas-bnatural.jpg',
    tags: ['libre de tóxicos', 'vegano', 'cruelty free'],
    is_featured: false, is_available: true, sort_order: 9,
  },
  {
    id: 'p-10', slug: 'lima-vidrio-templado-hooli', name: 'Lima de Vidrio Templado Hooli',
    brand: 'Hooli', category_id: 'cat-3',
    short_desc: 'Lima de cristal, doble cara, empaque 100% compostable.',
    description: 'Lima de cristal de alta calidad disponible en colores variados, con doble cara de limado para moldear y dar forma con mayor eficacia. Empaque 100% libre de plástico y compostable.',
    benefits: ['Alta duración', 'Doble cara', 'Empaque compostable', 'Sin plástico'],
    price: 25000, price_label: '',
    image_url: '/productos/base-unas-bnatural.jpg',
    tags: ['eco-friendly', 'compostable', 'sin plástico'],
    is_featured: false, is_available: true, sort_order: 10,
  },
  {
    id: 'p-11', slug: 'removedor-unas-libre-acetona-bnatural', name: 'Removedor para Uñas Libre de Acetona Bnatural',
    brand: 'Bnatural', category_id: 'cat-3',
    short_desc: 'Elimina el esmalte sin acetona ni tolueno.',
    description: 'No contiene acetona ni tolueno. Está diseñado para remover esmalte tradicional sin maltratar la uña ni la piel. Fórmula gentil y efectiva.',
    benefits: ['Sin acetona', 'Sin tolueno', 'Gentil con la uña', 'Efectivo'],
    price: 18000, price_label: '',
    image_url: '/productos/base-unas-bnatural.jpg',
    tags: ['sin acetona', 'libre de tóxicos', 'vegano'],
    is_featured: false, is_available: true, sort_order: 11,
  },
  // ─── HIGIENE PERSONAL ────────────────────────────────
  {
    id: 'p-12', slug: 'desodorante-vegano-sin-aluminio-hooli', name: 'Desodorante Vegano Sin Aluminio Hooli',
    brand: 'Hooli', category_id: 'cat-4',
    short_desc: 'Vegano, sin aluminio, sin alcohol. Protección natural eficaz.',
    description: 'Desodorante 100% vegano y libre de aluminio. Formulado con ingredientes naturales que neutralizan el olor sin bloquear la transpiración natural del cuerpo.',
    ingredients: 'Cera de candelilla, aceite de coco, óxido de zinc, aceite de ricino, almidón de tapioca, capric triglyceride, manteca de karité, bicarbonato de sodio, aceite esencial de eucalipto.',
    benefits: ['Sin aluminio', 'Vegano', 'Sin alcohol', 'Protección natural'],
    price: 32000, price_label: '',
    image_url: '/productos/desodorante-hooli.jpg',
    tags: ['vegano', 'sin aluminio', 'natural', 'eco-friendly'],
    is_featured: true, is_available: true, sort_order: 12,
  },
  {
    id: 'p-13', slug: 'crema-dental-sin-fluor-pastillas-oiris', name: 'Crema Dental sin Flúor en Pastillas Oiris',
    brand: 'Oiris', category_id: 'cat-4',
    short_desc: '120 pastillas sin flúor. Limpieza natural con arcilla y menta.',
    description: 'Pasta dental en formato de pastillas, sin flúor. Formulada con arcilla blanca, carbonato de calcio y aceite esencial de menta piperita. Higiene dental natural y efectiva.',
    ingredients: 'Arcilla blanca, carbonato de calcio, aceite de coco, aceite esencial de menta piperita.',
    benefits: ['Sin flúor', 'Limpieza efectiva', 'Formato sólido', '120 pastillas'],
    price: 32000, price_label: '/ 120 pastillas',
    image_url: '/productos/crema-dental-oiris.jpg',
    tags: ['sin flúor', 'natural', 'zero waste', 'vegano'],
    is_featured: false, is_available: true, sort_order: 13,
  },
  {
    id: 'p-14', slug: 'cepillo-dientes-bambu-uma', name: 'Cepillo de Dientes de Bambú UMA',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Bambú 100% natural. Biodegradable, duración 3 meses.',
    description: 'Fabricado con bambú 100% natural. El cepillo tiene una vida útil de aproximadamente 3 meses. Una alternativa sostenible a los cepillos de plástico convencionales.',
    benefits: ['Bambú natural', 'Biodegradable', 'Duración 3 meses', 'Eco-friendly'],
    price: 7000, price_label: '',
    image_url: '/productos/cepillo-bambu.jpg',
    tags: ['bambú', 'biodegradable', 'zero waste', 'natural'],
    is_featured: false, is_available: true, sort_order: 14,
  },
  {
    id: 'p-15', slug: 'seda-dental-biodegradable-uma', name: 'Seda Dental Biodegradable UMA',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'A base de maíz, en envase de vidrio reutilizable. 100% biodegradable.',
    description: 'Elaborada a base de maíz en envase de vidrio reutilizable. Materiales 100% biodegradables. Una elección consciente para tu higiene dental diaria.',
    benefits: ['100% biodegradable', 'Envase de vidrio', 'Base de maíz', 'Zero waste'],
    price: 19000, price_label: '',
    image_url: '/productos/cepillo-bambu.jpg',
    tags: ['biodegradable', 'zero waste', 'vegano', 'natural'],
    is_featured: false, is_available: true, sort_order: 15,
  },
  {
    id: 'p-16', slug: 'balsamo-labial-menta-hooli', name: 'Bálsamo Labial Menta Hooli',
    brand: 'Hooli', category_id: 'cat-4',
    short_desc: 'Bálsamo labial natural con menta, cacao y vitamina E.',
    description: 'Bálsamo labial formulado con aceites naturales y manteca de cacao. Hidrata, nutre y protege los labios con un suave aroma a menta.',
    ingredients: 'Aceite de coco, cera de candelilla, manteca de cacao, vitamina E, aceite esencial de menta, aceite de almendra dulce, ácido esteárico, aceite de ricino.',
    benefits: ['Hidratante', 'Protector', 'Vitamina E', 'Aroma natural de menta'],
    price: 27000, price_label: '',
    image_url: '/productos/cepillo-bambu.jpg',
    tags: ['vegano', 'natural', 'sin parabenos'],
    is_featured: false, is_available: true, sort_order: 16,
  },
  {
    id: 'p-17', slug: 'jabon-artesanal-afeitar-natiu', name: 'Jabón Artesanal para Afeitar Natiú',
    brand: 'Natiú', category_id: 'cat-4',
    short_desc: 'Fórmula natural con caléndula. Reemplaza espumas sintéticas.',
    description: 'Fórmula 100% natural diseñada para reemplazar espumas de afeitar sintéticas. Contiene caléndula con propiedades calmantes que evitan enrojecimiento e irritación post afeitado.',
    ingredients: 'Jabón artesanal de ceniza, caléndula y aceites naturales.',
    benefits: ['100% natural', 'Calmante', 'Anti-irritación', 'Suave e hidratante'],
    price: 19000, price_label: '',
    image_url: '/productos/jabon-afeitar-natiu.jpg',
    tags: ['natural', 'artesanal', 'caléndula', 'vegano'],
    is_featured: false, is_available: true, sort_order: 17,
  },
  {
    id: 'p-18', slug: 'maquina-metalica-reutilizable', name: 'Máquina Metálica Reutilizable',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Afeitadora metálica de larga duración con cuchillas intercambiables.',
    description: 'Corte limpio con cuchillas intercambiables. Reduce el uso de plásticos desechables. Una inversión consciente para toda la vida.',
    benefits: ['Larga duración', 'Sin plástico', 'Cuchillas intercambiables', 'Eco-friendly'],
    price: 28000, price_label: '',
    image_url: '/productos/jabon-afeitar-natiu.jpg',
    tags: ['sin plástico', 'eco-friendly', 'reutilizable', 'zero waste'],
    is_featured: false, is_available: true, sort_order: 18,
  },
  {
    id: 'p-19', slug: 'shampoo-barba-uma', name: 'Shampoo para Barba UMA',
    brand: 'UMA', category_id: 'cat-4',
    short_desc: 'Árbol de té y menta. Reduce caspa y vellos encarnados.',
    description: 'Formulado con aceites esenciales de árbol de té y menta. Ayuda a reducir la caspa en la barba, la aparición de vellos encarnados y granitos.',
    ingredients: 'Aceites esenciales de árbol de té y menta.',
    benefits: ['Reduce caspa', 'Previene vellos encarnados', 'Purificante', 'Refrescante'],
    price: 17000, price_label: '',
    image_url: '/productos/jabon-afeitar-natiu.jpg',
    tags: ['natural', 'árbol de té', 'grooming'],
    is_featured: false, is_available: true, sort_order: 19,
  },
  // ─── CUIDADO CORPORAL ────────────────────────────────
  {
    id: 'p-20', slug: 'jabon-corporal-miel-almendras', name: 'Jabón Corporal de Miel y Leche de Almendras',
    brand: 'Gala Elemento', category_id: 'cat-5',
    short_desc: 'Jabón artesanal hipoalergénico. Ideal para pieles sensibles.',
    description: 'Jabón natural libre de sulfatos y fragancias artificiales. Ideal para pieles sensibles, hipoalergénico y profundamente hidratante.',
    ingredients: 'Miel pura, leche de almendras, glicerina vegetal de palma de coco, fragancia vegetal de flor del Japón.',
    benefits: ['Hipoalergénico', 'Hidratante', 'Sin sulfatos', 'Pieles sensibles'],
    price: 22000, price_label: '',
    image_url: '/productos/jabon-miel-almendras.jpg',
    tags: ['artesanal', 'natural', 'pieles sensibles', 'vegano'],
    is_featured: true, is_available: true, sort_order: 20,
  },
  {
    id: 'p-21', slug: 'jabon-corporal-aloe-vera-oiris', name: 'Jabón Corporal de Aloe Vera Oiris',
    brand: 'Oiris', category_id: 'cat-5',
    short_desc: 'Reduce inflamación, calma alergias, regenera la piel.',
    description: 'Ayuda a reducir la inflamación, aliviar quemaduras solares, calmar alergias y estimular la regeneración celular. Enriquecido con aloe vera puro.',
    benefits: ['Antiinflamatorio', 'Regenerador celular', 'Calmante', 'Hidratante'],
    price: 39900, price_label: '',
    image_url: '/productos/jabon-intimo-oiris.jpg',
    tags: ['aloe vera', 'natural', 'piel sensible', 'vegano'],
    is_featured: false, is_available: true, sort_order: 21,
  },
  {
    id: 'p-22', slug: 'jabon-corporal-sal-rosada-himalaya', name: 'Jabón Corporal de Sal Rosada del Himalaya',
    brand: 'Gala Elemento', category_id: 'cat-5',
    short_desc: 'Exfolia suavemente y mejora la textura de la piel.',
    description: 'Exfolia suavemente, estimula la regeneración celular y mejora visiblemente la textura de tu piel. Con sal rosada del Himalaya de origen natural.',
    benefits: ['Exfoliante suave', 'Regenerador', 'Mejora textura', 'Mineralizante'],
    price: 36000, price_label: '',
    image_url: '/productos/jabon-intimo-oiris.jpg',
    tags: ['exfoliante', 'sal himalaya', 'natural', 'artesanal'],
    is_featured: false, is_available: true, sort_order: 22,
  },
  {
    id: 'p-23', slug: 'jabon-intimo-natural-oiris', name: 'Jabón Íntimo Natural Oiris',
    brand: 'Oiris', category_id: 'cat-5',
    short_desc: 'Respeta el pH y la flora vaginal. Previene infecciones.',
    description: 'Limpia delicadamente sin alterar el pH ni la flora vaginal. Sus aceites cuidadosamente seleccionados ayudan a prevenir infecciones como la candidiasis.',
    benefits: ['Respeta el pH', 'Protege flora vaginal', 'Previene candidiasis', 'Gentil'],
    price: 18000, price_label: '/ 55gr',
    image_url: '/productos/jabon-intimo-oiris.jpg',
    tags: ['íntimo', 'pH balanceado', 'natural', 'vegano'],
    is_featured: false, is_available: true, sort_order: 23,
  },
  {
    id: 'p-24', slug: 'protector-solar-extractos-naturales-econativa', name: 'Protector Solar Econativa SPF 50+',
    brand: 'Econativa', category_id: 'cat-5',
    short_desc: 'SPF 50+, ingredientes naturales, hipoalergénico, cruelty free.',
    description: 'Protector solar con extractos naturales y biodegradables. SPF 50+, hipoalergénico y libre de parabenos. Ideal para pieles sensibles. Cruelty free.',
    ingredients: 'Caléndula, manzanilla, aloe vera, manteca de karité, pepino, germen de trigo, aceite de oliva, dióxido de titanio.',
    benefits: ['SPF 50+', 'Hipoalergénico', 'Sin parabenos', 'Cruelty free', 'Biodegradable'],
    price: 36000, price_label: '',
    image_url: '/productos/protector-solar-econativa.jpg',
    tags: ['SPF 50+', 'natural', 'cruelty free', 'biodegradable'],
    is_featured: true, is_available: true, sort_order: 24,
  },
  {
    id: 'p-25', slug: 'balsamo-huellitas-uma', name: 'Bálsamo Huellitas UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Para las patitas de tus mascotas. Hidrata y protege.',
    description: 'Bálsamo natural especialmente formulado para las patitas de tus mascotas. Hidrata, nutre y protege con ingredientes 100% naturales.',
    ingredients: 'Aceite de coco, manteca de karité y manteca de cacao.',
    benefits: ['Para mascotas', 'Hidratante', 'Protector', '100% natural'],
    price: 27000, price_label: '/ 15gr',
    image_url: '/productos/balsamo-huellitas.jpg',
    tags: ['mascotas', 'natural', 'vegano'],
    is_featured: false, is_available: true, sort_order: 25,
  },
  {
    id: 'p-26', slug: 'roll-on-descanso-uma', name: 'Roll On Descanso UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Relaja mente y cuerpo. Facilita el sueño y la concentración.',
    description: 'Ayuda a relajar mente y cuerpo, facilitando el descanso y la concentración. Aceite corporal 100% natural en cómodo formato roll-on.',
    benefits: ['Relajante', 'Facilita el sueño', 'Mejora la concentración', '100% natural'],
    price: 26000, price_label: '/ 10ml',
    image_url: '/productos/roll-on-descanso.jpg',
    tags: ['roll-on', 'relajante', 'natural', 'aromaterapia'],
    is_featured: true, is_available: true, sort_order: 26,
  },
  {
    id: 'p-27', slug: 'roll-on-sana-uma', name: 'Roll On Sana UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Aceites antiinflamatorios para dolores musculares y articulares.',
    description: 'Aceites esenciales antiinflamatorios y analgésicos. Mejora dolores articulares, óseos y musculares. Formato práctico roll-on para aplicar directamente.',
    benefits: ['Antiinflamatorio', 'Analgésico', 'Dolores musculares', 'Dolores articulares'],
    price: 26000, price_label: '/ 10ml',
    image_url: '/productos/roll-on-sana.jpg',
    tags: ['roll-on', 'antiinflamatorio', 'natural', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 27,
  },
  {
    id: 'p-28', slug: 'roll-on-energia-uma', name: 'Roll On Energía UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Activa el cuerpo, estimula la circulación y la digestión.',
    description: 'Creado para generar una sensación de enfoque y activación en todo el cuerpo. Estimula la circulación y favorece la digestión.',
    benefits: ['Energizante', 'Estimula circulación', 'Favorece la digestión', 'Enfoque mental'],
    price: 26000, price_label: '/ 10ml',
    image_url: '/productos/roll-on-energia.jpg',
    tags: ['roll-on', 'energizante', 'natural', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 28,
  },
  {
    id: 'p-29', slug: 'pomada-botanica-calendula-uma', name: 'Pomada Botánica y de Caléndula UMA',
    brand: 'UMA', category_id: 'cat-5',
    short_desc: 'Botiquín natural: alivia, desinflamar y cicatriza.',
    description: 'Hacen parte de nuestro botiquín natural. Pomada Botánica: alivia, desinflamar, ideal para resfriados. Pomada de Caléndula: antiinflamatoria, cicatrizante y antiséptica.',
    ingredients: 'Aceites y ceras vegetales con extractos botánicos y caléndula.',
    benefits: ['Antiinflamatoria', 'Cicatrizante', 'Antiséptica', 'Botiquín natural'],
    price: 36000, price_label: '/ 40gr',
    image_url: '/productos/aceite-barba-natiu.jpg',
    tags: ['botiquín natural', 'caléndula', 'vegano', 'natural'],
    is_featured: false, is_available: true, sort_order: 29,
  },
  // ─── CUIDADO PARA ÉL ─────────────────────────────────
  {
    id: 'p-30', slug: 'aceite-para-barba-natiu', name: 'Aceite Para Barba Natiú',
    brand: 'Natiú', category_id: 'cat-6',
    short_desc: 'Mezcla premium de aceites vegetales para toda longitud de barba.',
    description: 'Mezcla premium de aceites vegetales hidratantes y aromáticos, ideales para cualquier longitud de barba.',
    ingredients: 'Aceite de oliva, almendra, coco, argán, aguacate y ricino.',
    benefits: ['Hidratante', 'Suavizante', 'Aromático', 'Para toda longitud'],
    price: 29900, price_label: '',
    image_url: '/productos/aceite-barba-natiu.jpg',
    tags: ['barba', 'natural', 'aceite vegetal', 'grooming'],
    is_featured: false, is_available: true, sort_order: 30,
  },
  {
    id: 'p-31', slug: 'crema-hidratante-barra-hooli', name: 'Crema Hidratante en Barra Hooli',
    brand: 'Hooli', category_id: 'cat-6',
    short_desc: 'Vegana, sin parabenos. Naranja con cacao y jojoba. Empaque compostable.',
    description: 'Elaborada con ingredientes completamente naturales y veganos, sin parabenos ni químicos agresivos. Presentada en un empaque biodegradable y compostable. Formato sólido naranja con manteca de cacao y aceite de jojoba.',
    ingredients: 'Manteca de cacao, aceite de jojoba, fragancia natural de naranja.',
    benefits: ['Vegana', 'Sin parabenos', 'Empaque compostable', 'Formato sólido'],
    price: 39900, price_label: '',
    image_url: '/productos/aceite-barba-natiu.jpg',
    tags: ['vegano', 'zero waste', 'compostable', 'natural'],
    is_featured: false, is_available: true, sort_order: 31,
  },
  // ─── SNACKS Y BIENESTAR ──────────────────────────────
  {
    id: 'p-32', slug: 'almendras-uma', name: 'Almendras UMA',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Almendras naturales seleccionadas.',
    description: 'Almendras naturales de alta calidad, seleccionadas cuidadosamente. Un snack nutritivo y consciente.',
    benefits: ['Alta proteína', 'Grasas saludables', 'Natural', 'Sin aditivos'],
    price: 5000, price_label: '/ bolsa',
    image_url: '/productos/almendras.jpg',
    tags: ['snack', 'natural', 'sin aditivos', 'proteína vegetal'],
    is_featured: false, is_available: true, sort_order: 32,
  },
  {
    id: 'p-33', slug: 'cardamomo-uma', name: 'Cardamomo UMA',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Especia aromática de primera calidad.',
    description: 'Cardamomo de primera calidad. Aromático, digestivo y lleno de antioxidantes. Perfecto para infusiones y recetas.',
    benefits: ['Digestivo', 'Antioxidante', 'Aromático', 'Especiería natural'],
    price: 7500, price_label: '/ bolsa',
    image_url: '/productos/almendras.jpg',
    tags: ['especia', 'natural', 'digestivo', 'aromático'],
    is_featured: false, is_available: true, sort_order: 33,
  },
  {
    id: 'p-34', slug: 'nuez-del-brasil-uma', name: 'Nuez del Brasil UMA',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Rica en selenio. Snack natural y nutritivo.',
    description: 'Nuez del Brasil de alta calidad. Fuente natural de selenio, grasas saludables y proteínas. Un snack consciente y nutritivo.',
    benefits: ['Rica en selenio', 'Grasas saludables', 'Alta proteína', 'Natural'],
    price: 8500, price_label: '/ bolsa',
    image_url: '/productos/almendras.jpg',
    tags: ['snack', 'selenio', 'natural', 'proteína vegetal'],
    is_featured: false, is_available: true, sort_order: 34,
  },
  {
    id: 'p-35', slug: 'vela-cera-vegetal-energia-uma', name: 'Vela de Cera Vegetal Energía UMA',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Vela de cera vegetal con aroma energizante. Envase reutilizable.',
    description: 'Vela elaborada con cera vegetal 100% natural. Aroma energizante para crear ambientes de concentración y vitalidad. Envase de vidrio reutilizable.',
    benefits: ['Cera vegetal', 'Envase reutilizable', 'Sin parafina', 'Aroma natural'],
    price: 25000, price_label: '',
    image_url: '/productos/velas-cera-vegetal.jpg',
    tags: ['vegetal', 'sin parafina', 'eco-friendly', 'aromaterapia'],
    is_featured: false, is_available: true, sort_order: 35,
  },
  {
    id: 'p-36', slug: 'vela-cera-vegetal-calma-uma', name: 'Vela de Cera Vegetal Calma UMA',
    brand: 'UMA', category_id: 'cat-7',
    short_desc: 'Vela de cera vegetal con aroma relajante. Envase reutilizable.',
    description: 'Vela elaborada con cera vegetal 100% natural. Aroma relajante para crear ambientes de calma y bienestar. Envase de vidrio reutilizable.',
    benefits: ['Cera vegetal', 'Envase reutilizable', 'Sin parafina', 'Aroma relajante'],
    price: 25000, price_label: '',
    image_url: '/productos/velas-cera-vegetal.jpg',
    tags: ['vegetal', 'sin parafina', 'eco-friendly', 'aromaterapia'],
    is_featured: true, is_available: true, sort_order: 36,
  },
];

export const brandConfig = {
  whatsapp_number: '',
  hero_tagline: 'Lo que le das a tu cuerpo, se lo das al mundo.',
  hero_subtitle: 'Productos naturales, biocosmética y snacks conscientes para una vida más plena.',
  instagram_url: '',
  footer_text: 'UMA Mercado Consciente — Cuidamos de ti y del planeta.',
  meta_description: 'UMA Mercado Consciente — Catálogo de biocosmética, productos eco-amigables, cuidado personal y snacks saludables. Pedidos por WhatsApp.',
};

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const cat = categories.find(c => c.slug === categorySlug);
  if (!cat) return products;
  return products.filter(p => p.category_id === cat.id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.is_featured && p.is_available);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find(c => c.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.short_desc.toLowerCase().includes(q) ||
    p.tags.some(t => t.toLowerCase().includes(q)) ||
    p.benefits.some(b => b.toLowerCase().includes(q))
  );
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function generateWhatsAppUrl(product: Product, waNumber: string): string {
  const number = waNumber.replace(/\D/g, '') || '0000000000';
  const msg = `Hola UMA. Quisiera pedir: *${product.name}* — ${formatPrice(product.price)}${product.price_label || ''}. ¿Pueden confirmarme disponibilidad?`;
  return `https://wa.me/${number}?text=${encodeURIComponent(msg)}`;
}
